site:
  title: Jenkins
  url: https://docs.jenkins.com
  start_page: user-docs::index.adoc
content:
  sources:
    - url: https://github.com/Vandit1604/jenkins-docs.git
      branches: [main, 2.2, 2.3]
      start_paths: [docs/tutorials, docs/user-docs, docs/dev-docs, docs/solutions]
runtime:
  fetch: true
asciidoc:
  attributes:
    page-pagination: ''
    plugin: https://plugins.jenkins.io/

ui:
  bundle:
    url: https://github.com/Vandit1604/jenkins-ui-project/raw/main/build/ui-bundle.zip
    snapshot: true

# --ui-bundle-url=/home/vandit/gsoc-project-demo/jenkins-ui-project/build/ui-bundle.zip
