site:
  title: Jenkins
  url: https://docs.jenkins.com
  start_page: user-docs::installing-jenkins:index.adoc
content:
  sources:
    - url: https://github.com/Vandit1604/jenkins-docs.git
      branches: [main]
      start_paths: [docs/dev-docs, docs/tutorial, docs/user-docs]
runtime:
  fetch: true
ui:
  bundle:
    url: /home/vandit/gsoc-project-demo/jenkins-ui-project/build/ui-bundle.zip
    snapshot: true
# --ui-bundle-url=/home/vandit/gsoc-project-demo/jenkins-ui-project/build/ui-bundle.zip